"""The planner expert: turn an idea / outline into per-section writing plans.

:class:`PlannerExpert` takes a research *idea* (and optional experimental log) or
a provided :class:`~clio_author.experts.write_models.PaperOutline` and produces a
:class:`~clio_author.experts.write_models.SectionPlan` for each section -- the
argument decomposed into ordered tasks, the claims to make, the sources/evidence
each rests on, plus a refined word budget and citation hints. These plans are
exactly what the ``write`` / ``compose`` path already consumes (via the writer's
``section_plan`` payload key).

The outline is either accepted as given or generated by reusing compose's
:func:`~clio_author.experts.compose._build_outline` (no outline-gen prompt is
duplicated here). Each section's plan is requested as a single JSON object and
parsed with the reviewer's :func:`~clio_author.experts.reviewer._extract_json_object`.

Like the other experts this one never raises: missing inputs or any failure
produce an error-flagged :class:`AgentOutput` (appended once), and a section whose
plan JSON does not parse falls back to a :class:`SectionPlan` wrapping the bare
outline with empty tasks (counted in ``metadata["plan_errors"]``) rather than
aborting. It defaults to :class:`~clio_author.llm.client.EchoLLMClient` so the
harness runs offline (the echo path naturally exercises the graceful fallback).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from clio_author.experts.compose import _build_outline
from clio_author.experts.reviewer import _extract_json_object
from clio_author.experts.write_models import PaperOutline, SectionOutline, SectionPlan
from clio_author.harness.base import BaseAgent
from clio_author.harness.session import SessionContext
from clio_author.harness.types import AgentOutput, Message, Task
from clio_author.ingest.blocks import MemoryBlocks
from clio_author.llm.client import EchoLLMClient, LLMClient
from clio_author.tools.files import SafeFiles, wants_overwrite, write_artifacts

PLANNER_SYSTEM_PROMPT = (
    "You are the planning expert. For one paper section you produce a concrete "
    "writing plan -- the argument decomposed into ordered tasks, the claims to "
    "make, the sources/evidence each rests on, a word budget, and citation hints "
    "-- grounded in the provided material. Do not write prose; only the plan."
)

_PLAN_INSTRUCTIONS = (
    "Produce a writing plan for this one section as a fenced JSON block:\n"
    "```json\n"
    '{"tasks": ["<ordered writing step>"], "claims": ["<claim to make>"], '
    '"sources": ["<source/evidence the claim rests on>"], '
    '"word_budget": <int or null>, '
    '"citation_hints": ["<\\\\cite{key} placeholder, optional>"], '
    '"research_needed": <true if this section needs a literature search before '
    "drafting, else false>, "
    '"research_topics": ["<topic/query to research, only if research_needed>"]}\n'
    "```\n"
    "Keep the format precise; the JSON is parsed automatically."
)


class PlannerExpert(BaseAgent):
    """Expert that turns an idea / outline into per-section writing plans."""

    def __init__(self, llm: LLMClient | None = None, *, files: SafeFiles | None = None) -> None:
        """Build a planner expert.

        Args:
            llm: Completion client; defaults to :class:`EchoLLMClient` (offline).
            files: Optional :class:`SafeFiles` used to persist ``plan.json`` when
                ``payload["out_dir"]`` is provided.
        """
        super().__init__(
            role="planner",
            system_prompt=PLANNER_SYSTEM_PROMPT,
            llm=llm or EchoLLMClient(),
        )
        self._files = files

    def _error(self, session: SessionContext, message: str) -> AgentOutput:
        output = AgentOutput(agent=self.name, content="", metadata={"error": message})
        session.add(output)
        return output

    def run(self, task: Task, session: SessionContext) -> AgentOutput:
        """Plan every section of the resolved outline from ``task.payload``.

        Reads ``idea`` (required unless an ``outline`` is given),
        ``experimental_log``, ``outline`` (a :class:`PaperOutline`/loose dict),
        ``blocks``/``source`` (optional grounding context), ``candidates``/
        ``citation_hints`` (optional), and ``out_dir``.

        Resolves the outline (provided, or generated by reusing compose's
        ``_build_outline``), then makes one LLM call per section for a JSON plan
        and builds a :class:`SectionPlan` (with the section's word budget and
        citation hints merged in). A section whose plan JSON does not parse falls
        back to a plan wrapping the bare outline with empty tasks (counted in
        ``metadata["plan_errors"]``). Returns one :class:`AgentOutput`
        (``agent="planner"``) whose ``structured`` is
        ``{"outline", "plans"}`` and whose ``metadata`` carries
        ``num_sections`` / ``num_tasks`` / ``wrote`` / ``plan_errors``. Persists
        ``plan.json`` under ``out_dir`` when reachable. Never raises: missing
        inputs or any failure produce an error-flagged output (appended once).
        """
        try:
            return self._run(task, session)
        except Exception as exc:  # noqa: BLE001 - experts never raise
            return self._error(session, str(exc))

    def _run(self, task: Task, session: SessionContext) -> AgentOutput:
        payload = task.payload
        idea = str(payload.get("idea") or "").strip()
        experimental_log = str(payload.get("experimental_log") or "").strip()

        outline = _build_outline(payload, idea, experimental_log, self.llm)
        if outline is None:
            if not idea and payload.get("outline") is None:
                return self._error(session, "no 'idea' and no 'outline' provided")
            return self._error(session, "could not parse generated outline")
        if not outline.sections:
            return self._error(session, "outline has no sections")

        grounding = self._grounding(payload)
        extra_hints = self._extra_hints(payload)

        plans: list[SectionPlan] = []
        plan_errors = 0
        for section in outline.sections:
            plan, ok = self._plan_section(section, outline, grounding, extra_hints)
            plans.append(plan)
            if not ok:
                plan_errors += 1

        num_tasks = sum(len(plan.tasks) for plan in plans)
        wrote, write_skipped = self._maybe_write(task, outline, plans)

        summary = f"Planned {len(plans)} sections, {num_tasks} tasks total."
        output = AgentOutput(
            agent=self.name,
            content=summary,
            structured={
                "outline": outline.model_dump(),
                "plans": [plan.model_dump() for plan in plans],
            },
            metadata={
                "num_sections": len(plans),
                "num_tasks": num_tasks,
                "wrote": wrote,
                **({"write_skipped": write_skipped} if write_skipped else {}),
                "plan_errors": plan_errors,
            },
        )
        session.add(output)
        return output

    @staticmethod
    def _grounding(payload: dict[str, Any]) -> str:
        """Assemble optional grounding context from ``blocks`` / ``source``."""
        blocks_raw = payload.get("blocks")
        if blocks_raw is not None:
            blocks = (
                blocks_raw
                if isinstance(blocks_raw, MemoryBlocks)
                else MemoryBlocks.model_validate(blocks_raw)
                if isinstance(blocks_raw, dict)
                else None
            )
            if blocks is not None:
                rendered = blocks.select(detail="summary")
                if rendered:
                    return "\n\n".join(rendered)
        source = payload.get("source")
        if source:
            return source if isinstance(source, str) else str(source)
        return ""

    @staticmethod
    def _extra_hints(payload: dict[str, Any]) -> list[str]:
        """Collect optional citation hints from ``candidates`` / ``citation_hints``."""
        hints: list[str] = []
        for key in ("citation_hints", "candidates"):
            raw = payload.get(key)
            if isinstance(raw, (list, tuple)):
                for item in raw:
                    text = str(item).strip()
                    if text:
                        hints.append(text)
            elif isinstance(raw, str) and raw.strip():
                hints.append(raw.strip())
        return hints

    def _plan_section(
        self,
        section: SectionOutline,
        outline: PaperOutline,
        grounding: str,
        extra_hints: list[str],
    ) -> tuple[SectionPlan, bool]:
        """Plan one section; return ``(plan, parsed_ok)``.

        On a parse failure, falls back to a :class:`SectionPlan` wrapping the bare
        ``section`` with empty tasks (``parsed_ok`` is ``False``).
        """
        messages = self._plan_messages(section, outline, grounding)
        raw_text = self.llm.complete(messages)
        parsed = _extract_json_object(raw_text)
        if parsed is None:
            return SectionPlan(outline=section), False

        merged_outline = self._merge_outline(section, parsed, extra_hints)
        plan_dict = dict(parsed)
        plan_dict["outline"] = merged_outline
        return SectionPlan.from_loose_dict(plan_dict), True

    @staticmethod
    def _merge_outline(
        section: SectionOutline,
        parsed: dict[str, Any],
        extra_hints: list[str],
    ) -> SectionOutline:
        """Merge a refined word budget / citation hints / research flags back in."""
        update: dict[str, Any] = {}

        raw_budget = parsed.get("word_budget")
        if raw_budget is not None:
            try:
                update["word_budget"] = int(round(float(raw_budget)))
            except (TypeError, ValueError):
                pass

        # Carry the planner's research decision onto the section so the writing
        # path (and the research expert) can act on it.
        raw_topics = parsed.get("research_topics")
        topics: list[str] = list(section.research_topics)
        if isinstance(raw_topics, (list, tuple)):
            topics.extend(str(t).strip() for t in raw_topics if str(t).strip())
        elif isinstance(raw_topics, str) and raw_topics.strip():
            topics.append(raw_topics.strip())
        # De-dupe preserving order.
        seen_topics: set[str] = set()
        deduped_topics: list[str] = []
        for topic in topics:
            if topic not in seen_topics:
                seen_topics.add(topic)
                deduped_topics.append(topic)
        if deduped_topics != list(section.research_topics):
            update["research_topics"] = deduped_topics

        raw_research = parsed.get("research_needed")
        research_needed = section.research_needed
        if raw_research is not None:
            if isinstance(raw_research, bool):
                research_needed = raw_research
            elif isinstance(raw_research, str):
                research_needed = raw_research.strip().lower() in {"true", "yes", "1"}
            else:
                research_needed = bool(raw_research)
        # A section with research topics implicitly needs research.
        research_needed = research_needed or bool(deduped_topics)
        if research_needed != section.research_needed:
            update["research_needed"] = research_needed

        hints: list[str] = list(section.citation_hints)
        raw_hints = parsed.get("citation_hints")
        if isinstance(raw_hints, (list, tuple)):
            hints.extend(str(h).strip() for h in raw_hints if str(h).strip())
        elif isinstance(raw_hints, str) and raw_hints.strip():
            hints.append(raw_hints.strip())
        hints.extend(extra_hints)
        # De-dupe preserving order.
        seen: set[str] = set()
        deduped: list[str] = []
        for hint in hints:
            if hint not in seen:
                seen.add(hint)
                deduped.append(hint)
        if deduped != list(section.citation_hints):
            update["citation_hints"] = deduped

        return section.model_copy(update=update) if update else section

    def _plan_messages(
        self, section: SectionOutline, outline: PaperOutline, grounding: str
    ) -> list[Message]:
        parts: list[str] = []
        if outline.vision:
            parts.append(f"Paper vision:\n{outline.vision}")
        parts.append(f"Section: {section.section_path or section.title}")
        if section.goal:
            parts.append(f"Goal of this section:\n{section.goal}")
        if section.word_budget:
            parts.append(f"Current target length: about {section.word_budget} words.")
        if section.citation_hints:
            parts.append(
                "Existing citation placeholders:\n"
                + "\n".join(f"- {hint}" for hint in section.citation_hints)
            )
        if grounding:
            parts.append(f"Grounding material:\n{grounding}")
        parts.append(_PLAN_INSTRUCTIONS)
        return [
            Message(role="system", content=self.system_prompt),
            Message(role="user", content="\n\n".join(parts)),
        ]

    def _maybe_write(
        self, task: Task, outline: PaperOutline, plans: list[SectionPlan]
    ) -> tuple[list[str], list[str]]:
        """Persist ``plan.json`` under ``out_dir`` when given.

        Mirrors :meth:`clio_author.experts.kg.KGExpert._maybe_write`: when the
        expert was constructed with a :class:`SafeFiles`, ``out_dir`` is a
        subdirectory under that sandbox root; otherwise ``out_dir`` is taken as
        the output root directly (the common CLI/adapter case). Best-effort /
        never-raise: the folder is minted once and a refused write is skipped.
        """
        out_dir = task.payload.get("out_dir")
        if not out_dir:
            return [], []

        if self._files is not None:
            files = self._files
            prefix = f"{out_dir}/"
        else:
            files = SafeFiles(Path(str(out_dir)))
            prefix = ""

        try:
            (files.root / prefix).mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            return [], [f"{out_dir}: {exc}"]

        structured = {
            "outline": outline.model_dump(),
            "plans": [plan.model_dump() for plan in plans],
        }
        return write_artifacts(
            files,
            ((f"{prefix}plan.json", json.dumps(structured, indent=2)),),
            overwrite=wants_overwrite(task.payload),
        )


__all__ = ["PlannerExpert", "PLANNER_SYSTEM_PROMPT"]
